### ISSUE TITLE
Maintenance notice

### ISSUE THREAD

**Issue by alexfedoseev** [parkerziegler/bs-emotion#16]
Hey folks, I decided to go w/ another CSS solution in my app so I won't be able to contribute to this project much since I don't use it myself anymore. The only todo left on my list here is to fix CI to add windows support to ppx, will do soon.

If anyone interested in maintaining this project, please, leave a comment here. Cheers.

**Comment by parkerziegler** [comment]
@alexfedoseev Out of curiosity, what was the other CSS solution you went with? I really like `bs-emotion` and would be interested in trying to land support for Emotion 10 if you want to transfer it over to me!

**Comment by alexfedoseev** [comment]
>  I really like bs-emotion and would be interested in trying to land support for Emotion 10 if you want to transfer it over to me!

Sure thing, will do 👍 

> Out of curiosity, what was the other CSS solution you went with?

I'm using [`linaria`](https://github.com/callstack/linaria). CSS is in JS files (i.e. untyped pure css strings) and I use ad-hoc script to generate bindings to files with styles so classnames/variables are typed and available on Reason site.

> I'm also just starting to get into PPX development and this looks like a good place to start. Any recommended readings on how to write a PPX?

My blog repo is in dirty state w/ started post about PPX but I don't feel like I finish it soon.
Here are few useful links:

Posts:
https://twitter.com/alexfedoseev/status/1040145415629197314

API docs:
https://caml.inria.fr/pub/docs/manual-ocaml/libref/Ast_helper.html
https://caml.inria.fr/pub/docs/manual-ocaml/libref/Parsetree.html
http://caml.inria.fr/cgi-bin/viewvc.cgi/ocaml/trunk/parsing/parsetree.mli?revision=16532&view=markup

Repos:
https://github.com/ocaml-ppx/ppx_tools (convinient way to explore ast)
https://github.com/jchavarri/hello-ppx-esy (building ppx w/ esy/dune instead of bsb-native)
https://github.com/ocaml-ppx/ocaml-migrate-parsetree (use up-to-date parsetree api in not so up-to-date bsb's ocaml)

**Comment by alexfedoseev** [comment]
Request sent.

**Comment by parkerziegler** [comment]
Thanks so much @alexfedoseev! Looks like the request expired (I wasn't online at all yesterday). Mind sending it one more time?

**Comment by alexfedoseev** [comment]
Sure, done.

**Comment by parkerziegler** [comment]
Thanks a bunch @alexfedoseev, and thanks again for all your work on this! I look forward to carrying on the torch.
